import type { FormationCode, TeamBuilderSlot } from "@/lib/data/types"

export const formationOptions: FormationCode[] = [
  "4-3-3",
  "4-4-2",
  "4-1-3-2",
  "4-2-3-1",
  "5-3-2",
  "5-2-3",
]

export const formationLayouts: Record<FormationCode, TeamBuilderSlot[]> = {
  "4-3-3": [
    { id: "gk", code: "GK", role: "Arquero", x: 50, y: 88 },
    { id: "lb", code: "LB", role: "Defensor", x: 12, y: 64 },
    { id: "lcb", code: "LCB", role: "Defensor", x: 38, y: 71 },
    { id: "rcb", code: "RCB", role: "Defensor", x: 62, y: 71 },
    { id: "rb", code: "RB", role: "Defensor", x: 88, y: 64 },
    { id: "lcm", code: "LCM", role: "Medio", x: 32, y: 46 },
    { id: "rcm", code: "RCM", role: "Medio", x: 50, y: 56 },
    { id: "lm", code: "LM", role: "Medio", x: 68, y: 46 },
    { id: "lcf", code: "LCF", role: "Delantero", x: 28, y: 22 },
    { id: "cf", code: "CF", role: "Delantero", x: 50, y: 16 },
    { id: "rcf", code: "RCF", role: "Delantero", x: 72, y: 22 },
  ],
  "4-4-2": [
    { id: "gk", code: "GK", role: "Arquero", x: 50, y: 88 },
    { id: "lb", code: "LB", role: "Defensor", x: 12, y: 64 },
    { id: "lcb", code: "LCB", role: "Defensor", x: 38, y: 71 },
    { id: "rcb", code: "RCB", role: "Defensor", x: 62, y: 71 },
    { id: "rb", code: "RB", role: "Defensor", x: 88, y: 64 },
    { id: "lm", code: "LM", role: "Medio", x: 12, y: 40 },
    { id: "lcm", code: "LCM", role: "Medio", x: 38, y: 48 },
    { id: "rcm", code: "RCM", role: "Medio", x: 62, y: 48 },
    { id: "rm", code: "RM", role: "Medio", x: 88, y: 40 },
    { id: "lcf", code: "LCF", role: "Delantero", x: 39, y: 22 },
    { id: "rcf", code: "RCF", role: "Delantero", x: 61, y: 22 },
  ],
  "4-1-3-2": [
    { id: "gk", code: "GK", role: "Arquero", x: 50, y: 88 },
    { id: "lb", code: "LB", role: "Defensor", x: 12, y: 64 },
    { id: "lcb", code: "LCB", role: "Defensor", x: 38, y: 71 },
    { id: "rcb", code: "RCB", role: "Defensor", x: 62, y: 71 },
    { id: "rb", code: "RB", role: "Defensor", x: 88, y: 64 },
    { id: "cdm", code: "CDM", role: "Medio", x: 50, y: 56 },
    { id: "lcm", code: "LCM", role: "Medio", x: 30, y: 42 },
    { id: "cam", code: "CAM", role: "Medio", x: 50, y: 34 },
    { id: "rcm", code: "RCM", role: "Medio", x: 70, y: 42 },
    { id: "lcf", code: "LCF", role: "Delantero", x: 38, y: 20 },
    { id: "rcf", code: "RCF", role: "Delantero", x: 62, y: 20 },
  ],
  "4-2-3-1": [
    { id: "gk", code: "GK", role: "Arquero", x: 50, y: 88 },
    { id: "lb", code: "LB", role: "Defensor", x: 12, y: 64 },
    { id: "lcb", code: "LCB", role: "Defensor", x: 38, y: 71 },
    { id: "rcb", code: "RCB", role: "Defensor", x: 62, y: 71 },
    { id: "rb", code: "RB", role: "Defensor", x: 88, y: 64 },
    { id: "lcdm", code: "LCDM", role: "Medio", x: 38, y: 54 },
    { id: "rcdm", code: "RCDM", role: "Medio", x: 62, y: 54 },
    { id: "lam", code: "LAM", role: "Medio", x: 14, y: 36 },
    { id: "cam", code: "CAM", role: "Medio", x: 50, y: 30 },
    { id: "ram", code: "RAM", role: "Medio", x: 86, y: 36 },
    { id: "cf", code: "CF", role: "Delantero", x: 50, y: 15 },
  ],
  "5-3-2": [
    { id: "gk", code: "GK", role: "Arquero", x: 50, y: 88 },
    { id: "lwb", code: "LB", role: "Defensor", x: 10, y: 62 },
    { id: "lcb", code: "LCB", role: "Defensor", x: 28, y: 70 },
    { id: "cb", code: "CB", role: "Defensor", x: 50, y: 70 },
    { id: "rcb", code: "RCB", role: "Defensor", x: 72, y: 70 },
    { id: "rwb", code: "RB", role: "Defensor", x: 90, y: 62 },
    { id: "lcm", code: "LCM", role: "Medio", x: 32, y: 42 },
    { id: "cm", code: "CM", role: "Medio", x: 50, y: 54 },
    { id: "rcm", code: "RCM", role: "Medio", x: 68, y: 42 },
    { id: "lcf", code: "LCF", role: "Delantero", x: 38, y: 20 },
    { id: "rcf", code: "RCF", role: "Delantero", x: 62, y: 20 },
  ],
  "5-2-3": [
    { id: "gk", code: "GK", role: "Arquero", x: 50, y: 88 },
    { id: "lwb", code: "LB", role: "Defensor", x: 10, y: 62 },
    { id: "lcb", code: "LCB", role: "Defensor", x: 28, y: 70 },
    { id: "cb", code: "CB", role: "Defensor", x: 50, y: 70 },
    { id: "rcb", code: "RCB", role: "Defensor", x: 72, y: 70 },
    { id: "rwb", code: "RB", role: "Defensor", x: 90, y: 62 },
    { id: "lcm", code: "LCM", role: "Medio", x: 36, y: 44 },
    { id: "rcm", code: "RCM", role: "Medio", x: 64, y: 44 },
    { id: "lcf", code: "LCF", role: "Delantero", x: 28, y: 22 },
    { id: "cf", code: "CF", role: "Delantero", x: 50, y: 16 },
    { id: "rcf", code: "RCF", role: "Delantero", x: 72, y: 22 },
  ],
}
