import { withSupabase } from "npm:@supabase/server@1.5.3"
const BASE="https://api.promiedos.com.ar",XVER="1.11.7.5",RIVER="igi",BA="America/Argentina/Buenos_Aires",SOURCE_TZ="America/Los_Angeles",BACKFILL_FROM=Date.parse("2026-07-01T00:00:00-03:00")
const LEAGUES=[{id:"hc",competition:"league" as const},{id:"gea",competition:"Copa Argentina" as const},{id:"dij",competition:"Copa Sudamericana" as const}]
type Competition="Torneo Apertura"|"Torneo Clausura"|"Copa Sudamericana"|"Copa Argentina"|"Amistoso";type Mode="fixtures"|"today"|"backfill_recent";type Status="upcoming"|"played";type Side="river"|"opponent"
type Team={id?:string;name?:string;short_name?:string;url_name?:string};type Game={id?:string;league?:{id?:string;name?:string};teams?:Team[];scores?:number[];penalties?:number[];status?:{enum?:number;name?:string};start_time?:string;stage_round_name?:string;tv_networks?:Array<{name?:string}>;game_info?:Array<{name?:string;value?:string}>;players?:any;events?:any[]};type Filter={key?:string;selected?:boolean;games?:Game[]}
type Existing={id:string;date:string;opponent:string;competition:Competition;status:Status;is_home:boolean;stadium:string;tv_channel:string|null;river_score:number|null;opponent_score:number|null;referee:string|null;detail:any;updated_by:string|null;promiedos_game_id:string|null}
type Detail={sourceLabel:string;referee?:string;resultNote?:string;penaltyShootout?:{river:number;opponent:number;winner:Side;kicks?:{river:Array<{player:string;scored:boolean}>;opponent:Array<{player:string;scored:boolean}>}};goals:Array<{team:Side;player:string;minute:string;assist?:string;detail?:string}>;cards:Array<{team:Side;player:string;minute:string;card:"yellow"|"red"}>;substitutions:Array<{team:Side;minute:string;playerIn:string;playerOut:string}>;lineups:{river:{coach:string;starters:string[];substitutes:string[]};opponent:{coach:string;starters:string[];substitutes:string[]}}}
type Normalized={promiedosGameId:string;date:string;opponent:string;competition:Competition;status:Status;isHome:boolean;stadium?:string;referee?:string|null;tvChannel:string|null;riverScore:number|null;opponentScore:number|null;detail?:Detail|null}
export default{fetch:withSupabase({auth:"none"},async(req,ctx)=>{if(req.method!=="POST")return Response.json({ok:false,error:"Method not allowed"},{status:405});let mode:Mode="fixtures";try{const b=await req.json();if(b?.mode==="today"||b?.mode==="backfill_recent")mode=b.mode;else if(b?.mode&&b.mode!=="fixtures")return Response.json({ok:false,error:"Invalid sync mode"},{status:400})}catch{}try{const{data,error}=await ctx.supabaseAdmin.from("matches").select("id,date,opponent,competition,status,is_home,stadium,tv_channel,river_score,opponent_score,referee,detail,updated_by,promiedos_game_id");if(error)throw error;const existing=(data??[]) as Existing[];let source:Normalized[];if(mode==="today")source=await today(true);else if(mode==="backfill_recent")source=await backfill(existing);else source=await fixtures();const games=dedupe(source),summary={mode,found:games.length,inserted:0,updated:0,unchanged:0},changed:any[]=[];for(const g of games){const e=find(existing,g),p=payload(g,e);if(e){if(!diff(e,p)){summary.unchanged++;continue}const{error}=await ctx.supabaseAdmin.from("matches").update(p).eq("id",e.id);if(error)throw error;Object.assign(e,p);summary.updated++;changed.push(compact(e.id,g))}else{const row={id:`promiedos-${g.promiedosGameId}`,...p};const{error}=await ctx.supabaseAdmin.from("matches").insert(row);if(error)throw error;existing.push(row as Existing);summary.inserted++;changed.push(compact(row.id,g))}}return Response.json({ok:true,...summary,games:changed})}catch(e){console.error("Promiedos River sync failed",e);return Response.json({ok:false,error:e instanceof Error?e.message:"Unknown sync error"},{status:500})}})}
async function fixtures(){const out:Normalized[]=[];for(const l of LEAGUES){for(const g of await leagueGames(l.id)){if(!riverGame(g))continue;const n=basic(g,l.competition);if(n)out.push(n)}}return out}
async function leagueGames(id:string){const d=await api(`/league/tables_and_fixtures/${id}`),games=collect(d),fs=(Array.isArray(d?.games?.filters)?d.games.filters:[]) as Filter[];let i=fs.findIndex(f=>f.selected===true);if(i<0)i=fs.findIndex(f=>Array.isArray(f.games)&&f.games.length>0);if(i<0)i=0;const filters=fs.slice(i).filter(f=>f.key&&f.key!=="latest");const rs=await Promise.allSettled(filters.map(f=>api(`/league/games/${id}/${encodeURIComponent(f.key!)}`)));for(const r of rs)if(r.status==="fulfilled")games.push(...collect(r.value));return games}
async function today(enrich:boolean){const d=await api(`/games/${dateBA(new Date())}`),out:Normalized[]=[];for(const l of Array.isArray(d?.leagues)?d.leagues:[]){const c=LEAGUES.find(x=>x.id===String(l?.id??""));if(!c)continue;for(const g of Array.isArray(l?.games)?l.games:[]){if(!riverGame(g))continue;const n=basic(g,c.competition);if(!n)continue;if(enrich&&n.status==="played")out.push(await detailed(n.promiedosGameId)??n);else out.push(n)}}return out}
async function backfill(existing:Existing[]){const t=await api(`/team/${RIVER}`),rows=Array.isArray(t?.games?.last?.rows)?t.games.last.rows:[],ids=new Set<string>();for(const row of rows){const g=row?.game as Game|undefined;if(!g?.id||g.status?.enum!==3||!g.start_time)continue;const k=kickoff(g.start_time);if(k&&k.getTime()>=BACKFILL_FROM)ids.add(g.id)}for(const m of existing){if(m.status!=="played"||!m.promiedos_game_id)continue;if(!m.detail||!m.referee||placeholder(m.stadium))ids.add(m.promiedos_game_id)}const ds=await mapLimit([...ids],4,detailed);return ds.filter((x):x is Normalized=>Boolean(x))}
async function detailed(id:string){const d=await api(`/gamecenter/${encodeURIComponent(id)}`),g=d?.game as Game|undefined;if(!g||!riverGame(g))return null;return normalizeDetail(g)}
function normalizeDetail(g:Game):Normalized|null{if(!g.id||!g.start_time||!g.teams||g.teams.length<2)return null;const k=kickoff(g.start_time);if(!k)return null;const c=competition(g,k),b=basic(g,c);if(!b)return null;const info=gameInfo(g);return{...b,stadium:info.stadium||"A confirmar",referee:info.referee,tvChannel:info.tv??b.tvChannel,detail:detail(g,b.isHome,b.opponent,info.referee)}}
function basic(g:Game,c:"league"|Competition):Normalized|null{if(!g.id||!g.start_time||!g.teams||g.teams.length<2)return null;const k=kickoff(g.start_time);if(!k)return null;const h=g.teams[0],a=g.teams[1],rh=riverTeam(h),ra=riverTeam(a);if(!rh&&!ra)return null;const o=rh?a:h,name=clean(o.name??o.short_name??"");if(!name)return null;const comp=c==="league"?infer(g,k):c,fin=g.status?.enum===3,s=Array.isArray(g.scores)?g.scores:[],hs=num(s[0])?Math.trunc(s[0]):null,as=num(s[1])?Math.trunc(s[1]):null;return{promiedosGameId:g.id,date:k.toISOString(),opponent:name,competition:comp,status:fin?"played":"upcoming",isHome:rh,tvChannel:g.tv_networks?.map(x=>x.name?.trim()).filter(Boolean).join(" / ")||null,riverScore:fin?(rh?hs:as):null,opponentScore:fin?(rh?as:hs):null}}
function competition(g:Game,k:Date):Competition{const id=g.league?.id,n=norm(g.league?.name??"");if(id==="hc")return infer(g,k);if(id==="dij"||n.includes("sudamericana"))return"Copa Sudamericana";if(id==="gea"||n.includes("copa argentina"))return"Copa Argentina";if(id==="dcb"||n.includes("amistoso"))return"Amistoso";return infer(g,k)}
function detail(g:Game,homeRiver:boolean,opponent:string,referee:string|null):Detail{const home:Side=homeRiver?"river":"opponent",away:Side=homeRiver?"opponent":"river",side=(n:number):Side=>n===1?home:away,events:any[]=[],penaltyStages:any[]=[];for(const st of Array.isArray(g.events)?g.events:[]){if(st?.is_penalties_stage)penaltyStages.push(st);else for(const row of Array.isArray(st?.rows)?st.rows:[])for(const e of Array.isArray(row?.events)?row.events:[])events.push(e)}const goals:Detail["goals"]=[];for(const e of events){const t=Number(e?.type);if(![1,2,3].includes(t))continue;const player=clean(String(e?.texts?.[0]??""));if(!player)continue;const assist=t===1?clean(String(e?.texts?.[1]??""))||undefined:undefined;goals.push({team:side(Number(e?.team)),player,minute:minute(String(e?.time??"")),...(assist?{assist}:{}),...(t===2?{detail:"Gol en contra"}:t===3?{detail:"Penal"}:{})})}const cards:Detail["cards"]=[];for(const e of events){const t=Number(e?.type);if(![4,5,6].includes(t))continue;const player=clean(String(e?.texts?.[0]??""));if(player)cards.push({team:side(Number(e?.team)),player,minute:minute(String(e?.time??"")),card:t===4?"yellow":"red"})}const substitutions:Detail["substitutions"]=[];for(const e of events){if(Number(e?.type)!==15)continue;const pi=clean(String(e?.texts?.[0]??"")),po=clean(String(e?.texts?.[1]??""));if(pi&&po)substitutions.push({team:side(Number(e?.team)),minute:minute(String(e?.time??"")),playerIn:pi,playerOut:po})}const ls=Array.isArray(g.players?.lineups?.teams)?g.players.lineups.teams:[],hl=ls.find((x:any)=>Number(x?.team_num)===1)??ls[0],al=ls.find((x:any)=>Number(x?.team_num)===2)??ls[1],rl=homeRiver?hl:al,ol=homeRiver?al:hl;const d:Detail={sourceLabel:"Promiedos",...(referee?{referee}:{}),goals,cards,substitutions,lineups:{river:lineup(rl),opponent:lineup(ol)}};if(Array.isArray(g.penalties)&&num(g.penalties[0])&&num(g.penalties[1])){const hp=Math.trunc(g.penalties[0]),ap=Math.trunc(g.penalties[1]),rp=homeRiver?hp:ap,op=homeRiver?ap:hp,kicks={river:[] as Array<{player:string;scored:boolean}>,opponent:[] as Array<{player:string;scored:boolean}>};for(const st of penaltyStages)for(const row of Array.isArray(st?.rows)?st.rows:[])for(const e of Array.isArray(row?.events)?row.events:[]){const t=Number(e?.type);if(![3,17].includes(t))continue;const p=clean(String(e?.texts?.[0]??""));if(p)kicks[side(Number(e?.team))].push({player:p,scored:t===3})}d.penaltyShootout={river:rp,opponent:op,winner:rp>op?"river":"opponent",kicks};d.resultNote=rp>op?"River ganó por penales":`${opponent} ganó por penales`}return d}
function lineup(l:any){const staff=Array.isArray(l?.staff)?l.staff:[],coach=clean(String((staff.find((p:any)=>norm(String(p?.formation_position??"")).includes("entrenador"))??staff[0])?.name??""))||"Sin dato";return{coach,starters:(Array.isArray(l?.starting)?l.starting:[]).map((p:any)=>clean(String(p?.name??""))).filter(Boolean),substitutes:(Array.isArray(l?.bench)?l.bench:[]).map((p:any)=>clean(String(p?.name??""))).filter(Boolean)}}
function gameInfo(g:Game){let stadium="",referee="",tv="";for(const i of Array.isArray(g.game_info)?g.game_info:[]){const k=norm(String(i?.name??"")),v=clean(String(i?.value??""));if(!v)continue;if(k==="estadio")stadium=v;else if(k.includes("arbitro"))referee=v;else if(k.includes("tv"))tv=v.replace(/,\s*/g," / ")}return{stadium,referee:referee||null,tv:tv||null}}
async function api(path:string){const r=await fetch(BASE+path,{headers:{Accept:"application/json","X-VER":XVER,"User-Agent":"Mozilla/5.0 (MedioRiverSync/1.0)",Referer:"https://www.promiedos.com.ar/"}});if(!r.ok)throw new Error(`Promiedos ${path} returned HTTP ${r.status}`);const d=await r.json();if(!d||typeof d!=="object")throw new Error(`Promiedos ${path} returned invalid data`);return d}
function collect(v:unknown,o:Game[]=[]):Game[]{if(!v||typeof v!=="object")return o;if(Array.isArray(v)){for(const x of v)collect(x,o);return o}const x=v as Record<string,unknown>;if(typeof x.id==="string"&&typeof x.start_time==="string"&&Array.isArray(x.teams)&&x.teams.length>=2){o.push(x as Game);return o}for(const n of Object.values(x))collect(n,o);return o}
function riverGame(g:Game){return g.teams?.some(riverTeam)??false}function riverTeam(t:Team){return t.id===RIVER||t.url_name==="river-plate"||norm(t.name??t.short_name??"")==="river plate"}
function infer(g:Game,k:Date):Competition{const d=norm(g.stage_round_name??"");if(d.includes("apertura"))return"Torneo Apertura";if(d.includes("clausura"))return"Torneo Clausura";return Number(new Intl.DateTimeFormat("en-US",{timeZone:BA,month:"numeric"}).format(k))<=6?"Torneo Apertura":"Torneo Clausura"}
function kickoff(v:string){const m=v.trim().match(/^(\d{2})-(\d{2})-(\d{4})\s+(\d{2}):(\d{2})$/);if(!m)return null;return wall(+m[3],+m[2],+m[1],+m[4],+m[5],SOURCE_TZ)}
function wall(y:number,m:number,d:number,h:number,mi:number,tz:string){const base=Date.UTC(y,m-1,d,h,mi),f=new Intl.DateTimeFormat("en-US",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}),p=Object.fromEntries(f.formatToParts(new Date(base)).map(x=>[x.type,x.value])),represented=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second),r=new Date(base-(represented-base));return Number.isNaN(r.getTime())?null:r}
function dateBA(d:Date){const p=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:BA,day:"2-digit",month:"2-digit",year:"numeric"}).formatToParts(d).map(x=>[x.type,x.value]));return`${p.day}-${p.month}-${p.year}`}
function find(es:Existing[],g:Normalized){const id=es.find(e=>e.promiedos_game_id===g.promiedosGameId);if(id)return id;const t=+new Date(g.date),max=72*3600e3;return es.find(e=>norm(e.opponent)===norm(g.opponent)&&Number.isFinite(+new Date(e.date))&&Math.abs(+new Date(e.date)-t)<=max)}
function payload(g:Normalized,e?:Existing){return{date:g.date,opponent:g.opponent,competition:g.competition,status:g.status,is_home:g.isHome,stadium:g.stadium||(e&&!placeholder(e.stadium)?e.stadium:"A confirmar"),tv_channel:g.tvChannel??e?.tv_channel??null,river_score:g.status==="played"?g.riverScore:null,opponent_score:g.status==="played"?g.opponentScore:null,referee:g.referee??e?.referee??null,detail:g.detail??e?.detail??null,updated_by:e?.updated_by??null,promiedos_game_id:g.promiedosGameId}}
function diff(e:Existing,p:ReturnType<typeof payload>){return e.date!==p.date||e.opponent!==p.opponent||e.competition!==p.competition||e.status!==p.status||e.is_home!==p.is_home||e.stadium!==p.stadium||e.tv_channel!==p.tv_channel||e.river_score!==p.river_score||e.opponent_score!==p.opponent_score||e.referee!==p.referee||JSON.stringify(e.detail??null)!==JSON.stringify(p.detail??null)||e.promiedos_game_id!==p.promiedos_game_id}
function placeholder(v:string|null|undefined){const n=norm(v??"");return!n||n==="a confirmar"||n.includes("sede a confirmar")}function dedupe(gs:Normalized[]){return[...new Map(gs.map(g=>[g.promiedosGameId,g])).values()]}function clean(v:string){return v.replace(/\s+/g," ").trim()}function norm(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}function minute(v:string){return v.replace(/'/g,"").replace(/\s+/g,"").trim()}function num(v:unknown):v is number{return typeof v==="number"&&Number.isFinite(v)}function compact(id:string,g:Normalized){return{id,promiedosGameId:g.promiedosGameId,date:g.date,opponent:g.opponent,competition:g.competition,score:g.status==="played"?`${g.riverScore}-${g.opponentScore}`:null,detail:Boolean(g.detail),stadium:g.stadium??null,referee:g.referee??null}}
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out=new Array<R>(items.length);let i=0;async function w(){for(;;){const n=i++;if(n>=items.length)break;out[n]=await fn(items[n])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},w));return out}
